FROM ros:humble-perception
RUN apt update
RUN apt install -y ros-humble-navigation2 ros-humble-nav2-bringup ros-humble-nav2-simple-commander ros-humble-slam-toolbox ros-humble-rviz2 

COPY ./nav2_default_view_humble.rviz /
